### ISSUE TITLE
A few typos (and congratulations)

### ISSUE THREAD

**Issue by npsqm** [dim0x69/embedded-systems-security-examples#1]
Hi Dimi,

first of all: Pretty impressive what you have done there! **Congratulations!** I just started reading your book. Unfortunately, I am not sure, when I will be able to continue reading, so I decided to let you know about a few typos already without collecting more of them:

- Chapter 2, last box: A newly introduced term is slways written in bold letters: slways => always
- Chapter 3.2: demistify => demystify
- Chapter 3.2: maschine => machine (multiple times)
- Chapter 3.2: A object => An object (multiple times, different cases)
- Chapter 3.2: broken structure: "The object file has a format, which we are going to focus on through this book is ELF (there are others). " =>(maybe)=> "The object file format which we are going to focus on throughout this book is ELF (there are others). "
- Chapter 3.2: "They do instruct the linker"  => Reference? Linker scripts ?
- Chapter 3.2: "When we talk of firmware" => talk about firmware
- Chapter 3.2: "In the following I am going to use the term build process, when I mean all three steps. " => "In the following, I am going to use the term build process to refer to all three steps. " (I think)

One more idea: For total noobs like me it might be nice to have a short paragraph in the introduction to explain: What is this TrustZone-M everyone is talking about?

Once again, great project! I am happy to see you enjoy your new freedom :)

Best,
Pascal

**Comment by dim0x69** [comment]
Hey Pascal,

thank you very much for your contribution, thats great! I just deployed a new version, which includes a fix and it should appear the next few hours after the cache expires. 

In a future version I'll also add a short paragraph introducing TrustZone-M. When I am deep into something, I tend to forget the most basic things ;) So thanks again! 

Dimi
