### ISSUE TITLE
Typo: Chapter 3.3

### ISSUE THREAD

**Issue by danewalton-msft** [dim0x69/embedded-systems-security-examples#6]
```
A object in C is a region of data storage. They have different propierties
```
A -> An
propierties -> properties

**Comment by danewalton-msft** [comment]
Also next sentence: `and assembler assembler always`

**Comment by dim0x69** [comment]
Thanks a lot @danewalton! I just pushed a new release, which fixed these typos. I also added 2 new chapters (9 and 10) with this release.
