### ISSUE TITLE
Various typos in chapter 3

### ISSUE THREAD

**Issue by jakr** [dim0x69/embedded-systems-security-examples#7]
Assembler example in 3.4.1:
current: this is the directive .word definind a variable
new: this is the directive .word, defining a variable

Chapter 3.5:
current: All secions have a section header
new: All sections have a section header

current: A segment is a collection of one or more sections and each segment has a program header
new: A segment is a collection of one or more sections, and each segment has a program header.
(comma inside, period at the end of the sentence)

current: For the linking view the segments are irrelevant.
new: For the linking view, the segments are irrelevant.
(this is just a suggestion)

current: If you want to skip directly to one specific, where is the list:
new: Here is the list, in case you directly want to skip to a specific one:

current: relocatable object file: holds code and data suitable for linking with other object files.
new: relocatable object file: holds code and data, suitable for linking with other object files.

current: executable object file: product of the linking of multiple relocatable.
new: executable object file: product of the linking of multiple relocatable object files.

current: The ELF header defines of which type an object file is.
new: The type of an object file is specified in its ELF header.

current: Let’s take a look at the most important fields in the ELF header (in parentheses the name used in the ELF specification. See [1] and for Arm specifics [2].
new: Let’s take a look at the most important fields in the ELF header. The name used in the ELF specification is in parentheses. See [1] and for Arm specifics [2].

current: Bit[0] of the Entry Point address is 1, so the processor will start in Arm Thumb mode. The compiler does specify that using the directive .thumb
new: ARM processors have two different instruction sets, a larger one called ARM and a smaller subset called Thumb. To distinguish between these two modes, Bit[0] of the address is used. If it is set to 0, the code will be executed in ARM mode, if it is set to 1, the code is executed in Thumb mode. In this case, Bit[0] of the Entry Point address is 1, so the processor will start in Thumb mode. The compiler does specify that using the directive .thumb

current: In relocatable object files st_value is the offset from the beginning of the section, where that symbol appears. In executable and shared object files st_value holds the virtual address of the symbol.
new: In relocatable object files, st_value is the offset from the beginning of the section, where that symbol appears. In executable and shared object files, st_value holds the virtual address of the symbol.

current: To do that take the same example as above and only compile it:
new: To do that, we take the same example as above and only compile it:

current: Symbols are expressions, so if the symbol extern_file_scope_var is used as expression and a appopriate symbol is not defined in the current object file - as in the example - the assembler will emit a undefined symbol with global linkage. 
new: Symbols are expressions, so if the symbol extern_file_scope_var is used as expression and a appopriate symbol is not defined in the current object file - as in the example -, the assembler will emit a undefined symbol with global linkage. 

current: In the exampe this resulted in a symbol in the symbol table with section index (Ndx) undefined.
new: In the example, this resulted in a symbol in the symbol table with section index (Ndx) undefined.

current: Imagine you have multiple relocatable object files, each of which has declared, not not initialized, the same file-scope object with external linkage. In one of them the object is initialized. Since each of these objects is part of one translation unit, neither the compiler nor the assembler now at compile and assembling time in which section to place this undefined objects (.bss or .data?) Only in the one translation unit where the object if initialized, the compiler knows: This should be placed in .data.
Further more, when none of the translation units initializes the object, space must be reserved in .bss!
new: Imagine that the compiler runs through multiple files. Each of them has declared the same file-scope object with external linkage, but none of them has initialized it. Since each of these files is part of one translation unit, neither the compiler nor the assembler now at compile and assembling time in which section to place this undefined objects (.bss or .data?). Only when the compiler comes across a file where the object is declared and initialized, it knows: This should be placed in .data.
If, however, none of the translation units initializes the object, space must be reserved in .bss!

current: This book currently covery only Armv8-M which only supports Thumb mode, so there is also no interworking necessary. 
new: This book currently only covers Armv8-M. Since this architecture only supports Thumb mode, no interworking is necessary.

**Comment by jakr** [comment]
One more thing: In the first code example in chapter 3.3, the comments are a bit hard to read. I would suggest to make the comments more similar to those in the second example.

old: int a; // file scope of a 
new: int a; // scope: file

old: static int b; // file scope of b
new: static int b; // scope: file

old: int a; // block scope of a. Hides the file scope a.
new: int a; // scope: block. Hides the previous a (which has file scope)

The section about declared, defined and initialized should mention why there is no difference between declared and defined for int.

**Comment by tsgowtham** [comment]
Found a typo in section 3.2
Current:  After the C Preprozessor combined c and h files into one
New: After the C Preprocessor combines the c and h files into one

**Comment by dim0x69** [comment]
Thanks a lot @tsgowtham and @jakr for these comments! I added all of them to the latest release, which I just pushed online.
I also added 2 new chapters (9 and 10)... all about STM32 :)
