### ISSUE TITLE
A small typo in basics of C language 

### ISSUE THREAD

**Issue by officialcjunior** [dim0x69/embedded-systems-security-examples#9]
On https://embeddedsecurity.io/sec-c.html there are four instances of two 'the'-s together.

* Defines global linkage for **the the** symbol global_linkage_file_scope_var.
* ll objects declared as static or extern have static storage duration. Linkage means, that the variable can be used in other scopes: Internal linkage meaning that the object can be used in all scopes of **the the** current translation unit,
* To influence **the the** visibility and lifetime of an object, you can change its storage class.
* The next step is to assemble **the the** compilers output (which is is written in assembly) into a object file.

I believe that they are small typos.

**Comment by dim0x69** [comment]
Thanks @officialcjunior :) 
Updated: https://embeddedsecurity.io/changelog
